let num1 = Number(prompt("insira um numero"))
let num2 = Number(prompt("insira outro numero"))
console.log("o primeiro numero é maior que o segundo?", num1 > num2)
console.log("o primeiro numero é igual ao segundo?", num1 === num2)
console.log("o primeiro numero é divisivel pelo segundo?", num1 % num2 === 0)
console.log("o segundo numero é divisivel pelo primeiro?", num2 % num1 === 0)